### ISSUE TITLE
Build with Pandoc Docker Image used By PartiQL Docs

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-spec#22]
This would enable us to use both Markdown and LaTeX in the specification and PSRs which would make the spec's markup more readable without taking away the ability to use LaTeX's when needed.

See: https://github.com/partiql/partiql-lang-kotlin/tree/master/docs/Docker for more details.

**Comment by jpschorr** [comment]
Obsoleted by #30 and #31
